/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaChef;

import Controlador.ControladorChef;
import Controlador.ControladorPersona;
import AF_Seleccion.Factory;
import AF_Factory.AbstractFactory;
import AF_Factory.FactoryMetodosTablasChef;
import java.awt.Color;

/**
 *
 * @author Erick
 */
public class ChefVista extends javax.swing.JFrame {

    /**
     * Creates new form Chef
     */
    private static ChefVista instancia;
    String tipo = "Chef";

    private ChefVista() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));

    }

    public static ChefVista getInstancia() {
        if (instancia == null) {
            instancia = new ChefVista();
        }
        return instancia;

    }

    public static AdicionarPlatillo A;
    public static ModificarPlatillo M;
    public static PlanificarMenu P;
    public static ModificarMenuSemanal MS;
    public static AtenderPedidoVirtual AP;
    public static PedidoEnProceso PP;
    ControladorChef C = ControladorChef.getInstancia();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreChef = new javax.swing.JLabel();
        txtDNIChef = new javax.swing.JLabel();
        RegistrarPlatillo = new javax.swing.JButton();
        PedidoProceso = new javax.swing.JButton();
        PlanificarM = new javax.swing.JButton();
        txtRolChef = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JButton();
        ModificarP = new javax.swing.JButton();
        ModificarMenu = new javax.swing.JButton();
        AtenderPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombreChef.setText("Valerio");

        txtDNIChef.setText("75140751");

        RegistrarPlatillo.setBackground(new java.awt.Color(87, 169, 154));
        RegistrarPlatillo.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarPlatillo.setText("REGISTRAR PLATILLO");
        RegistrarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPlatilloActionPerformed(evt);
            }
        });

        PedidoProceso.setBackground(new java.awt.Color(87, 169, 154));
        PedidoProceso.setForeground(new java.awt.Color(255, 255, 255));
        PedidoProceso.setText("PEDIDO EN PROCESO");
        PedidoProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoProcesoActionPerformed(evt);
            }
        });

        PlanificarM.setBackground(new java.awt.Color(87, 169, 154));
        PlanificarM.setForeground(new java.awt.Color(255, 255, 255));
        PlanificarM.setText("PLANIFICAR MENU SEMANAL");
        PlanificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlanificarMActionPerformed(evt);
            }
        });

        txtRolChef.setText("Chef");

        CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_close_pane_50px.png"))); // NOI18N
        CerrarSesion.setText("CERRAR SESION");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });

        ModificarP.setBackground(new java.awt.Color(87, 169, 154));
        ModificarP.setForeground(new java.awt.Color(255, 255, 255));
        ModificarP.setText("MODIFICAR PLATILLO");
        ModificarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPActionPerformed(evt);
            }
        });

        ModificarMenu.setBackground(new java.awt.Color(87, 169, 154));
        ModificarMenu.setForeground(new java.awt.Color(255, 255, 255));
        ModificarMenu.setText("MODIFICAR MENU SEMANAL");
        ModificarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarMenuActionPerformed(evt);
            }
        });

        AtenderPedido.setBackground(new java.awt.Color(87, 169, 154));
        AtenderPedido.setForeground(new java.awt.Color(255, 255, 255));
        AtenderPedido.setText("ATENDER PEDIDO");
        AtenderPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtenderPedidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BIENVENIDO CHEF");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_chef_120px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombreChef, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtDNIChef, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRolChef, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CerrarSesion)
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PlanificarM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(AtenderPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(PedidoProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(ModificarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RegistrarPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ModificarP)))
                                .addContainerGap(31, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRolChef, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreChef, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDNIChef)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AtenderPedido)
                                    .addComponent(PedidoProceso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PlanificarM)
                                .addGap(18, 18, 18)
                                .addComponent(ModificarMenu))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RegistrarPlatillo)
                                    .addComponent(ModificarP))
                                .addGap(131, 131, 131)))
                        .addGap(18, 18, 18)
                        .addComponent(CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPlatilloActionPerformed
        // ControladorChef C = ControladorChef.getInstancia();

        if (A == null && M == null && P == null && MS == null && AP == null && PP == null) {
            A = AdicionarPlatillo.getInstancia();
            C.JFrameAdicionar();
            AbstractFactory fabrica = Factory.getFactory(tipo);
            FactoryMetodosTablasChef tablaChef = fabrica.getTablaChef("PlatilloRegistradosChef");
            tablaChef.PlatilloRegistrados();

        }

    }//GEN-LAST:event_RegistrarPlatilloActionPerformed

    private void PlanificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlanificarMActionPerformed

        //ControladorChef C = ControladorChef.getInstancia();
        if (A == null && M == null && P == null && MS == null && AP == null && PP == null) {
            P = PlanificarMenu.getInstancia();

            C.JFramePlanificar();
            AbstractFactory fabrica = Factory.getFactory(tipo);
            FactoryMetodosTablasChef tablaChef = fabrica.getTablaChef("PlanificarMenuChef");
            tablaChef.PlanificarMenu();
        }
    }//GEN-LAST:event_PlanificarMActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        ControladorPersona controlador = ControladorPersona.getInstancia();

        if (A == null && M == null && P == null && MS == null && AP == null && PP == null) {
            controlador.JFrameIniciar();
            setVisible(false);
        }
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void ModificarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPActionPerformed
        //ControladorChef C = ControladorChef.getInstancia();
        if (A == null && M == null && P == null && MS == null && AP == null && PP == null) {
            M = ModificarPlatillo.getInstancia();

            C.JFrameModificarPlatillo();
            AbstractFactory fabrica = Factory.getFactory(tipo);
            FactoryMetodosTablasChef tablaChef = fabrica.getTablaChef("ModificarPlatilloChef");
            tablaChef.ModificarPlatillo();
        }
    }//GEN-LAST:event_ModificarPActionPerformed

    private void ModificarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarMenuActionPerformed
        //ControladorChef C = ControladorChef.getInstancia();
        if (A == null && M == null && P == null && MS == null && AP == null && PP == null) {
            MS = ModificarMenuSemanal.getInstancia();

            C.JFrameModificarMenuSemanal();
            AbstractFactory fabrica = Factory.getFactory(tipo);
            FactoryMetodosTablasChef tablaChef = fabrica.getTablaChef("ModificarMenuChef");
            tablaChef.ModificarMenu();
        }
    }//GEN-LAST:event_ModificarMenuActionPerformed

    private void PedidoProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoProcesoActionPerformed
        //ControladorChef C = ControladorChef.getInstancia();

        if (A == null && M == null && P == null && MS == null && AP == null && PP == null) {
            PP = PedidoEnProceso.getInstancia();
            C.JFramePedidoEnProceso();
            AbstractFactory fabrica = Factory.getFactory(tipo);
            FactoryMetodosTablasChef tablaChef = fabrica.getTablaChef("PedidoEnProcesoChef");
            tablaChef.PedidoEnProceso();
        }
    }//GEN-LAST:event_PedidoProcesoActionPerformed

    private void AtenderPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtenderPedidoActionPerformed

        //ControladorChef C = ControladorChef.getInstancia();
        if (A == null && M == null && P == null && MS == null && AP == null && PP == null) {
            AP = AtenderPedidoVirtual.getInstancia();
            C.JFrameAtenderPedido();
            AbstractFactory fabrica = Factory.getFactory(tipo);
            FactoryMetodosTablasChef tablaChef = fabrica.getTablaChef("AtenderPedidoChef");
            tablaChef.AtenderPedido();
        }


    }//GEN-LAST:event_AtenderPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChefVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChefVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChefVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChefVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChefVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AtenderPedido;
    private javax.swing.JButton CerrarSesion;
    public javax.swing.JButton ModificarMenu;
    public javax.swing.JButton ModificarP;
    public javax.swing.JButton PedidoProceso;
    public javax.swing.JButton PlanificarM;
    public javax.swing.JButton RegistrarPlatillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel txtDNIChef;
    public javax.swing.JLabel txtNombreChef;
    public javax.swing.JLabel txtRolChef;
    // End of variables declaration//GEN-END:variables
}
