/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaChef;

import VistaChef.ChefVista;
import DAO.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick
 */
public class ModificarPlatillo extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPlatillo
     */
    private static ModificarPlatillo instancia;

    private ModificarPlatillo() {
        initComponents();
setLocationRelativeTo(null);
this.getContentPane().setBackground(Color.decode("#FFFFFF"));
    }

    public static ModificarPlatillo getInstancia() {
        if (instancia == null) {
            instancia = new ModificarPlatillo();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPlatillo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CodigoB = new javax.swing.JTextField();
        Cargar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Codigo = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        Observaciones = new javax.swing.JTextField();
        ModificarPlatillo = new javax.swing.JButton();
        EliminarPlatillo = new javax.swing.JButton();
        Disponibilidad = new javax.swing.JTextField();
        CbModificarPlatillo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TablaPlatillo.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        TablaPlatillo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Observaciones", "Disponibilidad"
            }
        ));
        TablaPlatillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPlatilloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPlatillo);

        jLabel1.setText("CODIGO");

        Cargar.setBackground(new java.awt.Color(87, 169, 154));
        Cargar.setForeground(new java.awt.Color(255, 255, 255));
        Cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_cargar.png"))); // NOI18N
        Cargar.setText("CARGAR");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("CODIGO");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("NOMBRE");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("PRECIO");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("OBSERVACIONES");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("DISPONIBILIDAD");

        Codigo.setEditable(false);
        Codigo.setBackground(new java.awt.Color(255, 255, 255));
        Codigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Precio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Observaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        ModificarPlatillo.setBackground(new java.awt.Color(87, 169, 154));
        ModificarPlatillo.setForeground(new java.awt.Color(255, 255, 255));
        ModificarPlatillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_edit_property_30px.png"))); // NOI18N
        ModificarPlatillo.setText("MODIFICAR");

        EliminarPlatillo.setBackground(new java.awt.Color(87, 169, 154));
        EliminarPlatillo.setForeground(new java.awt.Color(255, 255, 255));
        EliminarPlatillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Delete_30px_1.png"))); // NOI18N
        EliminarPlatillo.setText("ELIMINAR");

        Disponibilidad.setEditable(false);
        Disponibilidad.setBackground(new java.awt.Color(255, 255, 255));
        Disponibilidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        CbModificarPlatillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CbModificarPlatillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No disponible" }));

        jLabel7.setBackground(new java.awt.Color(32, 32, 32));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 45, 45));
        jLabel7.setText("PLATILLOS BRISAS MARINAS");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setBorderPainted(false);
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(CodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Cargar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(ModificarPlatillo)
                                .addGap(27, 27, 27)
                                .addComponent(EliminarPlatillo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Observaciones)
                                            .addComponent(Nombre)
                                            .addComponent(Codigo)
                                            .addComponent(Precio)
                                            .addComponent(Disponibilidad)
                                            .addComponent(CbModificarPlatillo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel5))
                                .addGap(46, 46, 46)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cargar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(CbModificarPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModificarPlatillo)
                            .addComponent(EliminarPlatillo))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        DefaultTableModel modelo = new DefaultTableModel(); //agregar las filas a mi tabla
        TablaPlatillo.setModel(modelo);

        String campo = CodigoB.getText();
        String where = "";
        if (!campo.equals("")) {
            where = "where codigoPlatillo='" + campo + "'";
        }

        PreparedStatement ps = null; //hacer consulta a la bd
        ResultSet rs = null; //Obtener resultados de la consulta en la bd
        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();
            //Buscar todo
            //ps = conexion.prepareStatement("select codigo,nombre,precio,cantidad from producto");
            //Buscar especifico
            ps = conexion.prepareStatement("select distinct codigoPlatillo, nombrePlatillo, precioPlatillo, observacionesPlatillo, disponibilidadPlatillo from platillo " + where);
            rs = ps.executeQuery(); //executeQuery() cada que se queira obtener resultado de la BD
            //Si quiero modificar o eliminar uso el executeUpDate()

            modelo.addColumn("Codigo");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Observaciones");
            modelo.addColumn("Disponibilidad");

            //Le asignamos todo lo que hemos obtenido en nuestra BD
            ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount(); //Conteo exacto de mis columnas en mi tabla

            //ANCHO DE LAS COLUMNAS
            int anchos[] = {70, 100, 50, 100, 100};
            for (int i = 0; i < cantidadColumnas; i++) {
                //Traemos a nuestra tabla, vamos a obtener el modelo de las columnas
                //Vamos obtner cada una de las columnas y vamos a establacer el ancho predefinido
                TablaPlatillo.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }
            while (rs.next()) { //mientras aún haya registros en mi bd llenará la tabla
                Object fila[] = new Object[cantidadColumnas]; //creamos arreglo para cada una de las filas que vamos obteniendo
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            CodigoB.setText(null);

        } catch (SQLException ex) {
            System.err.println("Error, " + ex);
        }
    }//GEN-LAST:event_CargarActionPerformed

    private void TablaPlatilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPlatilloMouseClicked
        PreparedStatement ps = null; //hacer consulta a la bd
        ResultSet rs = null; //Obtener resultados de la consulta en la bd

        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();

            int fila = TablaPlatillo.getSelectedRow();
            String codigo = TablaPlatillo.getValueAt(fila, 0).toString();

            ps = conexion.prepareStatement("select  codigoPlatillo, nombrePlatillo, precioPlatillo, observacionesPlatillo, disponibilidadPlatillo from platillo where codigoPlatillo=?");
            ps.setString(1, codigo);
            rs = ps.executeQuery();

            while (rs.next()) {
                Codigo.setText(rs.getString("codigoPlatillo"));
                Nombre.setText(rs.getString("nombrePlatillo"));
                Precio.setText(String.valueOf(rs.getString("precioPlatillo")));
                Observaciones.setText(rs.getString("observacionesPlatillo"));
                Disponibilidad.setText(rs.getString("disponibilidadPlatillo"));

            }

        } catch (SQLException ex) {
            System.err.println("Error, " + ex);
        }

    }//GEN-LAST:event_TablaPlatilloMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       ChefVista.M = null;
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        ChefVista.M = null;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPlatillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPlatillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPlatillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPlatillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPlatillo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar;
    public javax.swing.JComboBox<String> CbModificarPlatillo;
    public javax.swing.JTextField Codigo;
    public javax.swing.JTextField CodigoB;
    public javax.swing.JTextField Disponibilidad;
    public javax.swing.JButton EliminarPlatillo;
    public javax.swing.JButton ModificarPlatillo;
    public javax.swing.JTextField Nombre;
    public javax.swing.JTextField Observaciones;
    public javax.swing.JTextField Precio;
    public javax.swing.JTable TablaPlatillo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
