/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaCliente;

import DAO.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PEDRO
 */
public class VerMenuSemanalCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormInformacionPlatillos
     */
    private static VerMenuSemanalCliente instancia;
    
    
    private VerMenuSemanalCliente() {
        initComponents();
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.decode("#FFFFFF"));
        
    }
    
    public static VerMenuSemanalCliente getInstancia() {
        if(instancia==null) {
            instancia=new VerMenuSemanalCliente();
        }
        return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Reservar = new javax.swing.JButton();
        Cantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamePlatillo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInformacionPlatillos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CbDia = new javax.swing.JComboBox<>();
        Cargar = new javax.swing.JButton();
        Dia = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        DNICliente = new javax.swing.JTextField();
        MostrarTodo = new javax.swing.JButton();
        IdPlatillo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Obs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(45, 45, 45)));

        Reservar.setBackground(new java.awt.Color(118, 219, 209));
        Reservar.setForeground(new java.awt.Color(255, 255, 255));
        Reservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_checkout_30px.png"))); // NOI18N
        Reservar.setText("Reservar");
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });

        Cantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Cantidad a Reservar");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Platillo");

        txtNamePlatillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNamePlatillo.setText("-");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Dia");

        txtDia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDia.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtNamePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(Reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reservar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tbInformacionPlatillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbInformacionPlatillos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInformacionPlatillosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbInformacionPlatillos);

        jLabel1.setBackground(new java.awt.Color(32, 32, 32));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 45, 45));
        jLabel1.setText("Informacion de Platillos");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("DIA");

        CbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO" }));
        CbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbDiaActionPerformed(evt);
            }
        });

        Cargar.setBackground(new java.awt.Color(87, 169, 154));
        Cargar.setForeground(new java.awt.Color(255, 255, 255));
        Cargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_cargar.png"))); // NOI18N
        Cargar.setText("CARGAR");
        Cargar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });

        Dia.setEditable(false);

        Nombre.setEditable(false);

        Precio.setEditable(false);

        DNICliente.setEditable(false);

        MostrarTodo.setBackground(new java.awt.Color(87, 169, 154));
        MostrarTodo.setForeground(new java.awt.Color(255, 255, 255));
        MostrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon_mostrar_todo.png"))); // NOI18N
        MostrarTodo.setText("MOSTRAR TODO");
        MostrarTodo.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodoActionPerformed(evt);
            }
        });

        IdPlatillo.setEditable(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setBorderPainted(false);
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Obs.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(CbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(MostrarTodo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(Obs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(DNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(IdPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(CbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Cargar))
                    .addComponent(MostrarTodo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Obs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
       
    }//GEN-LAST:event_ReservarActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
       //***CORREGIR///***
        
        DefaultTableModel modelo = new DefaultTableModel(); //agregar las filas a mi tabla
        tbInformacionPlatillos.setModel(modelo);
        
        String campo = (String) CbDia.getSelectedItem();
        String where = "";
        
        if(!"".equals(campo)) { //Si el campo no está vacio
            where = "where diaPlatillo='"+campo+"'";
        } 
        
        PreparedStatement ps = null; //hacer consulta a la bd
        ResultSet rs = null; //Obtener resultados de la consulta en la bd
        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();
            //Buscar todo
            //ps = conexion.prepareStatement("select codigo,nombre,precio,cantidad from producto");
            //Buscar especifico
            ps = conexion.prepareStatement("select idPlatillo, codigoPlatillo,diaPlatillo,nombrePlatillo,precioPlatillo,disponibilidadPlatillo from platillo "+where);
            rs = ps.executeQuery(); //executeQuery() cada que se queira obtener resultado de la BD
            //Si quiero modificar o eliminar uso el executeUpDate()
            
            modelo.addColumn("id");
            modelo.addColumn("Codigo");
            modelo.addColumn("Dia");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Disponibilidad");
            
            
            //Le asignamos todo lo que hemos obtenido en nuestra BD
            ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount(); //Conteo exacto de mis columnas en mi tabla
            
            
            //ANCHO DE LAS COLUMNAS
            int anchos[] = {20,50,80,100,50,100};
            for (int i = 0; i < cantidadColumnas; i++) {
                //Traemos a nuestra tabla, vamos a obtener el modelo de las columnas
                //Vamos obtner cada una de las columnas y vamos a establacer el ancho predefinido
                tbInformacionPlatillos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }           
            while(rs.next()) { //mientras aún haya registros en mi bd llenará la tabla
                Object fila[] = new Object[cantidadColumnas]; //creamos arreglo para cada una de las filas que vamos obteniendo
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rs.getObject(i+1); 
                }
                modelo.addRow(fila);
            } 
     
            
        } catch(SQLException ex) {
            System.err.println("Error, "+ex);
        }


       
    }//GEN-LAST:event_CargarActionPerformed

    private void tbInformacionPlatillosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInformacionPlatillosMouseClicked
          PreparedStatement ps = null; //hacer consulta a la bd
        ResultSet rs = null; //Obtener resultados de la consulta en la bd

        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();

            int fila = tbInformacionPlatillos.getSelectedRow();
            String id = tbInformacionPlatillos.getValueAt(fila, 0).toString();

            ps = conexion.prepareStatement("select idPlatillo, diaPlatillo, nombrePlatillo, precioPlatillo, disponibilidadPlatillo from platillo where idPlatillo=?");
            ps.setString(1, id);
            rs = ps.executeQuery();

            while (rs.next()) {
                txtNamePlatillo.setText(rs.getString("nombrePlatillo"));
                txtDia.setText(rs.getString("diaPlatillo"));
                IdPlatillo.setText(rs.getString("idPlatillo"));
                Dia.setText(rs.getString("diaPlatillo"));
                Nombre.setText(rs.getString("nombrePlatillo"));
                Precio.setText(String.valueOf(rs.getString("precioPlatillo")));
                Obs.setText(rs.getString("disponibilidadPlatillo"));
            }
        } catch (SQLException ex) {
            System.err.println("Error, " + ex);
        }
    }//GEN-LAST:event_tbInformacionPlatillosMouseClicked

    private void CbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbDiaActionPerformed

    }//GEN-LAST:event_CbDiaActionPerformed

    private void MostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodoActionPerformed
        DefaultTableModel modelo = new DefaultTableModel(); //agregar las filas a mi tabla
        tbInformacionPlatillos.setModel(modelo);     
        PreparedStatement ps = null; //hacer consulta a la bd
        ResultSet rs = null; //Obtener resultados de la consulta en la bd
        try {
            Conexion con = new Conexion();
            Connection conexion = con.getConnection();
            //Buscar todo
            //ps = conexion.prepareStatement("select codigo,nombre,precio,cantidad from producto");
            //Buscar especifico
            ps = conexion.prepareStatement("select idPlatillo, codigoPlatillo,diaPlatillo,nombrePlatillo,precioPlatillo,disponibilidadPlatillo from platillo order by diaPlatillo desc");
            rs = ps.executeQuery(); //executeQuery() cada que se queira obtener resultado de la BD
            //Si quiero modificar o eliminar uso el executeUpDate()
            
            modelo.addColumn("id");
            modelo.addColumn("Codigo");
            modelo.addColumn("Dia");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Disponibilidad");
            
            
            //Le asignamos todo lo que hemos obtenido en nuestra BD
            ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount(); //Conteo exacto de mis columnas en mi tabla
            
            
            //ANCHO DE LAS COLUMNAS
            int anchos[] = {20, 50,80,100,50,100};
            for (int i = 0; i < cantidadColumnas; i++) {
                //Traemos a nuestra tabla, vamos a obtener el modelo de las columnas
                //Vamos obtner cada una de las columnas y vamos a establacer el ancho predefinido
                tbInformacionPlatillos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }           
            while(rs.next()) { //mientras aún haya registros en mi bd llenará la tabla
                Object fila[] = new Object[cantidadColumnas]; //creamos arreglo para cada una de las filas que vamos obteniendo
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rs.getObject(i+1); 
                }
                modelo.addRow(fila);
            } 
     
            
        } catch(SQLException ex) {
            System.err.println("Error, "+ex);
        }
    }//GEN-LAST:event_MostrarTodoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ClienteVista.MS=null;
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        ClienteVista.MS=null;
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerMenuSemanalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerMenuSemanalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerMenuSemanalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerMenuSemanalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerMenuSemanalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Cantidad;
    public javax.swing.JButton Cargar;
    public javax.swing.JComboBox<String> CbDia;
    public javax.swing.JTextField DNICliente;
    public javax.swing.JTextField Dia;
    public javax.swing.JTextField IdPlatillo;
    private javax.swing.JButton MostrarTodo;
    public javax.swing.JTextField Nombre;
    public javax.swing.JTextField Obs;
    public javax.swing.JTextField Precio;
    public javax.swing.JButton Reservar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbInformacionPlatillos;
    public javax.swing.JLabel txtDia;
    public javax.swing.JLabel txtNamePlatillo;
    // End of variables declaration//GEN-END:variables
}
